### ISSUE TITLE
Error: Installing Plugin

### ISSUE THREAD

**Issue by ghost** [lorenzo132/modmail-plugins#14]
When I ran ">plugins add autorole", it did not add the plugin and this error message came up: "Invalid plugin name, double check the plugin name or use one of the following formats: username/repo/plugin, username/repo/plugin@branch." Please fix this. I was looking forward to having this plugin in my server.

**Comment by lorenzo132** [comment]
Try: `>plugin add lorenzo132/modmail-plugins/autorole`
